### ISSUE TITLE
Pop OS 22.04 Support (with Pipewire)

### ISSUE THREAD

**Issue by bfenty** [imustafin/razer-nari-pulseaudio-profile#22]
It's possible this is my own misunderstanding, but...

On a fresh install of Pop OS 22.04 I'm unable to get the Nari working properly. I've always used pulseaudio and that worked fine on the old version of Pop, but with the latest release they've switched to Pipewire and I can't get figure out how to get the profile installed. I figure lots of people will probably have the same question, so it would be worth posting it here for an answer.

Thank you!

**Comment by imustafin** [comment]
Hi. Can you please check if https://github.com/imustafin/razer-nari-pulseaudio-profile#pipewire the PipeWire instructions work?

Basically, you would need to
1. In `91-pulseaudio-razer-nari.rules` change `PULSE_PROFILE_SET` to `ACP_PROFILE_SET`
2. Instead of `/usr/share/pulseaudio/` use /usr/share/alsa-card-profile/`

If it works, a pull request with an updated README or other contributions are very welcome!

**Comment by bfenty** [comment]
Step 1 is what I had not done-from the README it seemed optional but is apparently mandatory.

I will try to update the README as a thank you for your help and a great piece of code. I love my Nari headset and getting to use it on Linux has been a real game-changer (no pun intended).
